language: node_js
node_js:
  - "0.12"
addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    packages: [ 'libstdc++6' ]
script: "npm run test-ci"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
